# 开发测试分支
# 
stages:
    - deploy
cache:
    untracked: true
    key: uni-apph5
    paths:
        - $(pwd)/.yarn-cache
        - node_modules/
uniapp2h5-release:
    stage: deploy
    script:
        - source /etc/profile
        - yarn
        - sed -i "s/{{why}}/$CI_PROJECT_NAME/g" src/manifest-ci.json
        - mv src/manifest-ci.json src/manifest.json -vf
        - yarn cross-env NODE_ENV=production UNI_PLATFORM=h5 vue-cli-service uni-build
        - rm "$public""$CI_PROJECT_NAME"/ -vrf
        - mkdir "$public""$CI_PROJECT_NAME"/ -p
        - mv  dist/build/h5/* "$public""$CI_PROJECT_NAME"/ -vf
        - mv "$public""$CI_PROJECT_NAME"/index.html "$public""$CI_PROJECT_NAME"/index.php -fv
        - touch "$public""$CI_PROJECT_NAME"/release.owo
        - touch "$public""$CI_PROJECT_NAME"/uni.owo
        - echo "=======正式版构建部署成功======"
        - echo "访问地址：https://dev.v0718.com/?-$CI_PROJECT_NAME-release-index-"
        - echo "备用地址：https://now.v0718.com/?-$CI_PROJECT_NAME-release-index-"
        - echo -e "\033[41;30m 注意路径中的release是keyid是为自定义的变量，上线后不可更改!所以如果已经上线的项目不要不同地址再发出去！！！其他变量及标记请到文档中查阅\033[0m"
    only:
        - release
uniapp2h5-test:
    stage: deploy
    script: 
        - source /etc/profile
        - keyid="`date +%Y%m%d`"
        - yarn
        - sed -i "s/{{why}}/$CI_PROJECT_NAME\/dev\//g" src/manifest-ci.json
        - mv src/manifest-ci.json src/manifest.json -vf
        - yarn cross-env NODE_ENV=development UNI_PLATFORM=h5 vue-cli-service uni-build
        - rm "$public""$CI_PROJECT_NAME"/dev/ -vrf
        - mkdir "$public""$CI_PROJECT_NAME"/dev/ -p
        - mv  dist/dev/h5/* "$public""$CI_PROJECT_NAME"/dev/ -vf
        - mv "$public""$CI_PROJECT_NAME"/dev/index.html "$public""$CI_PROJECT_NAME"/dev/index.php -fv
        - touch "$public""$CI_PROJECT_NAME"/dev/test.owo
        - touch "$public""$CI_PROJECT_NAME"/dev/uni.owo
        - echo "=======测试版构建部署成功======"
        - echo "访问地址：https://dev.v0718.com/?-$CI_PROJECT_NAME/dev-$keyid-index-"
        - echo "备用地址：https://now.v0718.com/?-$CI_PROJECT_NAME/dev-$keyid-index-"
        - echo -e "\033[41;30m 注意路径中的$keyid是keyid是为自定义的变量，上线后不可更改!所以如果已经上线的项目不要不同地址再发出去！！！其他变量及标记请到文档中查阅\033[0m"
        - echo -e "\033[41;30m 注意本链接仅用于内部测试，性能略低于正式版，若需要在chrome调试请在链接加入-nowx- ！\033[0m"
    only:
        - develop

